---
name: lint_build_and_publish
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - production
  schedule:
    - cron: "0 0 * * 0"

jobs:
  lint_el9:
    uses: ./.github/workflows/lint.yml
    with:
      codename: el9
      docker_image_name: ghcr.io/almalinux/9-base
      docker_image_tag: "9"

  lint_el10:
    uses: ./.github/workflows/lint.yml
    with:
      codename: el10
      docker_image_name: ghcr.io/almalinux/10-base
      docker_image_tag: "10"

  build_el9_x86_64:
    needs:
      - lint_el9
    uses: ./.github/workflows/build.yml
    with:
      codename: el9
      docker_image_name: ghcr.io/almalinux/9-base
      docker_image_tag: "9"
      runner_image: ubuntu-24.04
      sign: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  build_el9_aarch64:
    needs:
      - lint_el9
    uses: ./.github/workflows/build.yml
    with:
      codename: el9
      docker_image_name: ghcr.io/almalinux/9-base
      docker_image_tag: "9"
      runner_image: ubuntu-24.04-arm
      sign: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  build_el10_x86_64:
    needs:
      - lint_el10
    uses: ./.github/workflows/build.yml
    with:
      codename: el10
      docker_image_name: ghcr.io/almalinux/10-base
      docker_image_tag: "10"
      runner_image: ubuntu-24.04
      sign: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  build_el10_aarch64:
    needs:
      - lint_el10
    uses: ./.github/workflows/build.yml
    with:
      codename: el10
      docker_image_name: ghcr.io/almalinux/10-base
      docker_image_tag: "10"
      runner_image: ubuntu-24.04-arm
      sign: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  lint_fc43:
    uses: ./.github/workflows/lint.yml
    with:
      codename: fc43
      docker_image_name: registry.fedoraproject.org/fedora
      docker_image_tag: "43"

  build_fc43_x86_64:
    needs:
      - lint_fc43
    uses: ./.github/workflows/build.yml
    with:
      codename: fc43
      docker_image_name: registry.fedoraproject.org/fedora
      docker_image_tag: "43"
      runner_image: ubuntu-24.04
      sign: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  build_fc43_aarch64:
    needs:
      - lint_fc43
    uses: ./.github/workflows/build.yml
    with:
      codename: fc43
      docker_image_name: registry.fedoraproject.org/fedora
      docker_image_tag: "43"
      runner_image: ubuntu-24.04-arm
      sign: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  publish:
    needs:
      - build_el9_x86_64
      - build_el9_aarch64
      - build_el10_x86_64
      - build_el10_aarch64
      - build_fc43_x86_64
      - build_fc43_aarch64
    strategy:
      matrix:
        repository:
          - kubernetes
          - prometheus
          - incus
          - zfs
        docker_image:
          - name: ghcr.io/almalinux/9-base
            tag: 9
          - name: ghcr.io/almalinux/10-base
            tag: 10
          - name: registry.fedoraproject.org/fedora
            tag: 43
        runner_image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner_image }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          pattern: ${{ matrix.repository }}-rpms-*-${{ matrix.docker_image.tag }}-${{ matrix.runner_image }}
          merge-multiple: true
          path: RPMS/${{ matrix.repository }}
      - run: make SPEC_FILE=none DOCKER_IMAGE_NAME=${{ matrix.docker_image.name }} DOCKER_IMAGE_TAG=${{ matrix.docker_image.tag }} GPG_PRIVATE_KEY="${{ secrets.GPG_PRIVATE_KEY }}" GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }} YUM_REPOSITORIES_ACCESS_KEY=${{ secrets.YUM_REPOSITORIES_ACCESS_KEY }} YUM_REPOSITORIES_SECRET_KEY=${{ secrets.YUM_REPOSITORIES_SECRET_KEY }} YUM_REPOSITORIES_S3_ENDPOINT=${{ secrets.YUM_REPOSITORIES_S3_ENDPOINT }} YUM_REPOSITORIES_BUCKET_NAME=${{ secrets.YUM_REPOSITORIES_BUCKET_NAME }} YUM_REPOSITORY_NAME=${{ matrix.repository }} publish_in_docker
