---
name: lint_and_build
on:  # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - production

jobs:
  lint_el9:
    uses: ./.github/workflows/lint.yml
    with:
      codename: el9
      docker_image_name: ghcr.io/almalinux/9-base
      docker_image_tag: "9"

  lint_el10:
    uses: ./.github/workflows/lint.yml
    with:
      codename: el10
      docker_image_name: ghcr.io/almalinux/10-base
      docker_image_tag: "10"

  build_el9_x86_64:
    needs:
      - lint_el9
    uses: ./.github/workflows/build.yml
    with:
      codename: el9
      docker_image_name: ghcr.io/almalinux/9-base
      docker_image_tag: "9"
      runner_image: ubuntu-24.04

  build_el9_aarch64:
    needs:
      - lint_el9
    uses: ./.github/workflows/build.yml
    with:
      codename: el9
      docker_image_name: ghcr.io/almalinux/9-base
      docker_image_tag: "9"
      runner_image: ubuntu-24.04-arm

  build_el10_x86_64:
    needs:
      - lint_el10
    uses: ./.github/workflows/build.yml
    with:
      codename: el10
      docker_image_name: ghcr.io/almalinux/10-base
      docker_image_tag: "10"
      runner_image: ubuntu-24.04

  build_el10_aarch64:
    needs:
      - lint_el10
    uses: ./.github/workflows/build.yml
    with:
      codename: el10
      docker_image_name: ghcr.io/almalinux/10-base
      docker_image_tag: "10"
      runner_image: ubuntu-24.04-arm

  lint_fc44:
    uses: ./.github/workflows/lint.yml
    with:
      codename: fc44
      docker_image_name: registry.fedoraproject.org/fedora
      docker_image_tag: "44"

  build_fc44_x86_64:
    needs:
      - lint_fc44
    uses: ./.github/workflows/build.yml
    with:
      codename: fc44
      docker_image_name: registry.fedoraproject.org/fedora
      docker_image_tag: "44"
      runner_image: ubuntu-24.04

  build_fc44_aarch64:
    needs:
      - lint_fc44
    uses: ./.github/workflows/build.yml
    with:
      codename: fc44
      docker_image_name: registry.fedoraproject.org/fedora
      docker_image_tag: "44"
      runner_image: ubuntu-24.04-arm
