---
name: lint_and_build
on:  # yamllint disable-line rule:truthy
  - push

jobs:
  list_spec_files:
    runs-on: ubuntu-24.04
    outputs:
      spec_files: ${{ steps.list_spec_files.outputs.spec_files }}
    steps:
      - uses: actions/checkout@v4
      - id: list_spec_files
        run: |
          spec_files=$(ls SPECS | jq -R . | jq -c -s .)
          echo "spec_files=$spec_files" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-24.04
    needs:
      - list_spec_files
    strategy:
      matrix:
        spec_file: ${{ fromJson(needs.list_spec_files.outputs.spec_files) }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo make SPEC_FILE=SPECS/${{ matrix.spec_file }} lint_in_docker

  build:
    runs-on: ubuntu-24.04
    needs:
      - list_spec_files
      - lint
    strategy:
      matrix:
        spec_file: ${{ fromJson(needs.list_spec_files.outputs.spec_files) }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo make SPEC_FILE=SPECS/${{ matrix.spec_file }} build_in_docker
